### ISSUE TITLE
Working with multiple parameters

### ISSUE THREAD

**Issue by Anof-cyber** [PortSwigger/BChecks#10]
Can we work with all the given request parameters including query and body parameters and JSON? 

Assuming the request has 2 queries and 2 body parameters. Is it possible to add the payload to each parameter one by one and send 4 different requests?

**Comment by A-J-C** [comment]
Hi @Anof-cyber this would be an insertion point check "given insertion point then" if you don't specify a type of insertion point then the scanner will call the BCheck with each insertion point it has found.
