### ISSUE TITLE
Request feature - Response timeout

### ISSUE THREAD

**Issue by Pyvonix** [PortSwigger/BChecks#103]
Hi PortSwigger team,

I propose the add a response's keyword: `timeout` as boolean value to know when the request didn't get a respond from the server for vulns like DOS.

Thank you.

**Comment by Hannah-PortSwigger** [comment]
Thanks for the feedback! We've raised this as a feature request to be discussed further.

**Comment by Hannah-PortSwigger** [comment]
This is a similar feature request to #32 and #72

**Comment by Pyvonix** [comment]
Hi @Hannah-PortSwigger,

No, this feature is not about the time it takes to make a request (as explain in #32 ).

This enhancement is to provide a boolean to know when a request raises the [TimeoutException](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/util/concurrent/TimeoutException.html).

Use case: my BCheck made a request and DOS the backend. Who could I know my rule successfully works?
The sent request will not have any response, so I will not be able to trigger any finding.

**Comment by Michelle-PortSwigger** [comment]
I'll check with the team exactly which scenarios the feature request here would cover. For example, whether it will cover cases where there is no response from the server as well as delayed responses. I'll be in touch soon with an update.

**Comment by Michelle-PortSwigger** [comment]
Hi

I've checked with the team this morning, and we do have both scenarios covered in the feature requests we have created for further discussion and are monitoring here. I'll leave this open for now to make it clearer that both enhancements have been logged.

**Comment by Pyvonix** [comment]
Thank you,

Waiting to see the new feature to tell you if it covers this usage.
