### ISSUE TITLE
Error when using report issue and continue in BChecks editor

### ISSUE THREAD

**Issue by idealphase** [PortSwigger/BChecks#137]
First of all, I'd like to inform you that I'm new user for BChecks. I'm trying to create Bchecks script to check missing of security response headers for some reason.

According to action `report issue and continue` in https://portswigger.net/burp/documentation/scanner/bchecks/bcheck-definition-reference#actions
another use example: https://github.com/PortSwigger/BChecks/blob/e7ed2fcbed20c6e59208f895b50f42966152a534/examples/exposed-backup-file.bcheck#L24 

Currently, my Burp pro version is 2023.10.2.4.  I can use action `report issue` without getting any error.
However, when I try to change action from `report issue` to `report issue and continue` (on line 10) I found an error as shown in the following figure.
![report_issue_and_continue](https://github.com/PortSwigger/BChecks/assets/12832679/73bded93-d3f8-4f12-a795-21acd2b2ce92)

I'm not sure what I did wrong. Please help me to provide a recommendation. Thanks.

**Comment by PortSwiggerWiener** [comment]
Hi. Thanks for the report and the interest in BChecks.

The 'report issue and continue' construct is part of the v2-beta language version, which is currently on the Early Adopter channel. Can you please try version 2023.10.3.2 with 'v2-beta' within the metadata block?

**Comment by idealphase** [comment]
Hi @PortSwiggerWiener, Thank you so much for your response and detailed information. I've tried to update to version `2023.10.3.2` and change `language: v2-beta`. I didn't get an error any more. Thanks.

By the way, I'd be great if you put which one it only support on v2-beta on your [official documentation](https://portswigger.net/burp/documentation/scanner/bchecks/bcheck-definition-reference#actions) I think maybe other people will be confused like me.

**Comment by Hannah-PortSwigger** [comment]
Thanks for the feedback! We'll look at making this distinction between language versions clearer.

v2-beta should be available on the stable channel within a couple of weeks.

If there's anything else we can help with, then please let us know.
