### ISSUE TITLE
Access request parameters 

### ISSUE THREAD

**Issue by nbxiglk0** [PortSwigger/BChecks#146]
Hi,It would be nice to have an ability to get the current requests parameters , for example i want to passively identify base64 encoded parameters used in the original request or identify the parameter value in the request that uses an encoded special string. You need to identify such parameters first and then decode them for further judgment.

**Comment by nbxiglk0** [comment]
For example, I want to identify PHP serializable data in request parameters, and this type of data is generally transmitted in the form of base64 encoding. I need to get all the parameters of the request first, then base64 decode them in sequence, and then use regular expressions Make a match。

**Comment by nbxiglk0** [comment]
maybe i can loop insertion point to achieve it.

**Comment by Michelle-PortSwigger** [comment]
That sounds like a good idea. You can use insertion_point_base_value to do a regex match for base64 encoding and that should get you where you need to be.
