### ISSUE TITLE
Can't dns interactions be detected at given insertion point then?

### ISSUE THREAD

**Issue by chain00x** [PortSwigger/BChecks#16]
This is my code, and I know for sure that there will be a callback, but I'm reporting an error in the event log
 
<img width="922" alt="image" src="https://github.com/PortSwigger/BChecks/assets/90015694/cbddd56a-c1a1-4d56-b937-527c9401f18e">

This is my complete code

`metadata:
    language: v1-beta
    name: "Request-level collaborator based"
    description: "Blind SSRF with out-of-band detection"
    author: "Carlos Montoya"

given insertion point then
    send payload:
        replacing: {generate_collaborator_address()}
    if dns interactions then
        report issue:
            severity: high
            confidence: firm
            detail: "This site fetches arbitrary URLs specified in the Referer header."
            remediation: "Ensure that the site does not directly request URLs from the Referer header."
    end if`

**Comment by genuinemoses** [comment]
Hi @chain00x, could you elaborate what you're trying to achieve?
It looks like you want to insert a collaborator address to nested insertion points in a request to find potential OOB SSRF.
The code seems to work fine as executed by Burp Scanner.

**Comment by genuinemoses** [comment]
It looks like this is a valid issue, I've checked the interactions with external request capturing tools like http://pingb.in/ to confirm the issue.

The Bcheck definition may not be capturing the dns interactions. It could be the case that the Bcheck definition for `dns interactions` is not working as expected or it's misunderstood and misused.

Let's wait for the Portswigger team to respond and confirm if this is an issue.

@chain00x , @A-J-C ,@olliewuk

**Comment by chain00x** [comment]
Ok, look forward to solving the problem

**Comment by A-J-C** [comment]
Hi, we are currently looking into this issue and should be able to give you an update soon.

**Comment by A-J-C** [comment]
We've figured the issue out and have a fix in place. This will be live when 2023.6 hits stable later this week. 

Thank you very much for the report!
