### ISSUE TITLE
Naming convention issues

### ISSUE THREAD

**Issue by zjicmDarkWing** [PortSwigger/BChecks#18]
The bcheck file with the author "Carlos Montoya" in the example has problems, the name does not have a clear meaning, and it is difficult to confirm the usage based on the name after importing into Burp's BChecks

![Xnip2023-06-30_13-49-19](https://github.com/PortSwigger/BChecks/assets/8244926/3a802d3e-d06b-4704-a318-609d766b3fb3)

**Comment by A-J-C** [comment]
These are specifically named templates that allow you to quickly pick an existing BCheck to base a new one off of. They are not necessarily designed to be used as checks themselves as there is overlap with existing scan checks, as such they aren't named for that.
