### ISSUE TITLE
[BUG] SSRFInjection doesn't generate collaborator payload

### ISSUE THREAD

**Issue by AnoAlex** [PortSwigger/BChecks#201]
### Current behavior

https://github.com/PortSwigger/BChecks/blob/main/vulnerability-classes/injection/SSRFInjection.bcheck#L8

### Environment details

  - Burp version:
  - BCheck language version:
  - Operating System:

### Additional details
![image](https://github.com/PortSwigger/BChecks/assets/46762874/5f05e434-e2dd-46ab-bb8e-0b70ed0e7a3b)

**Comment by Hannah-PortSwigger** [comment]
Hi

I've double-checked this and it looks like it should be using backticks instead of speech marks.

I've put a pull request in to update this 🙂
