### ISSUE TITLE
Enhancement: Create a BChecks scan configuration in the built-in library 

### ISSUE THREAD

**Issue by DanaEpp** [PortSwigger/BChecks#24]
The default UI elements when building a custom scan configuration are a bit tedious to uncheck everything except "BCheck generated issues". Why not create a new Auditing configuration just for BChecks and add it to the built-in library?

![image](https://github.com/PortSwigger/BChecks/assets/11337016/3b290a3a-6a13-48ca-b0a4-46e2caadf342)

Call it "Audit checks - BCheck scripts only"  or something like that.

**Comment by A-J-C** [comment]
This does actually already exist, you can see it in use here: https://youtu.be/NaiQMJk4nus

Unfortunately, it didn't quite make it into the latest release, it will be in the next point release though!
