### ISSUE TITLE
How to define scanning depth

### ISSUE THREAD

**Issue by JaveleyQAQ** [PortSwigger/BChecks#3]
How to define the scanning depth, such as http://a.com/a/b/c/ . I would like to scan/a/payload first, then/a/b/payload, and then /a/b/c/payload

**Comment by A-J-C** [comment]
If you click the ? Icon in the top right of the BChecks sub tab in the Extensions tab you will be linked to the documentation. Where you'll be able to see the different ways of writing BChecks available to you.
