### ISSUE TITLE
Ability to filter bchecks in the dashboard

### ISSUE THREAD

**Issue by BuffaloWill** [PortSwigger/BChecks#39]
Is there a way to filter on bchecks in the issues section of the Dashboard (e.g. tags) without adding something custom to the name (e.g. "name: cve-xx-xxxx (bcheck)")? It would be nice to quickly filter on bcheck issues from other issues or having tags usable in the dashboard.

**Comment by Hannah-PortSwigger** [comment]
Thanks for the feedback! We don't currently have this functionality, but we'll get a feature request raised.
