### ISSUE TITLE
Can BCheck use passive scanning?  For example, in Response-level (passive) check, you need to initiate an active scan to view the result

### ISSUE THREAD

**Issue by hughink** [PortSwigger/BChecks#5]

**Comment by A-J-C** [comment]
I think since you've closed it you've realised, but one of the most powerful way to use BChecks is changing the config of your Live Audit task to also run BChecks. You can then just enable the passive BChecks and your Live Audit task will automatically run them for you.

**Comment by Hannah-PortSwigger** [comment]
Just to update this thread, passive BChecks are included in the default live passive tasks as of v2023.7.1.
