### ISSUE TITLE
Issuing requests to each directory in a URL

### ISSUE THREAD

**Issue by BuffaloWill** [PortSwigger/BChecks#6]
Is there a way to issue requests for each directory in a path? For example, let's say we want to look for `/.git/config` in each directory for the URL `http://foo.com/dir1/dir2/test.html`. That would result in three requests:

`GET http://foo.com/dir1/dir2/.git/config`
`GET http://foo.com/dir1/.git/config`
`GET http://foo.com/.git/config`

**Comment by olliewuk** [comment]
Closing due to answer of the question.

**Comment by Hannah-PortSwigger** [comment]
This feature request is continued in #86
