### ISSUE TITLE
NullPointerExcpetion  

### ISSUE THREAD

**Issue by JaveleyQAQ** [PortSwigger/BChecks#60]
I get prompts when using the case template as well. My Burp Suite version is 2023.7.

![image](https://github.com/PortSwigger/BChecks/assets/132129852/5cae2ce2-4264-41bb-bebb-fbc0912d2cd5)

**Comment by Hannah-PortSwigger** [comment]
Hi.

Could you drop us an email at support@portswigger.net so that we can look into this further, please?

Could you include your diagnostics information? You can find this by going to "Help > Diagnostics" within Burp.

**Comment by JaveleyQAQ** [comment]
> Hi.
> 
> Could you drop us an email at [support@portswigger.net](mailto:support@portswigger.net) so that we can look into this further, please?
> 
> Could you include your diagnostics information? You can find this by going to "Help > Diagnostics" within Burp.

already send it

**Comment by Michelle-PortSwigger** [comment]
Details were passed to support@portswigger.net. The BCheck being discussed has also been submitted to the repo since the last entry on this thread.
If there are any related outstanding issues, the thread can be re-opened.
