### ISSUE TITLE
Is `report and issue` the only way to get logged info back from a bcheck ?

### ISSUE THREAD

**Issue by Sim4n6** [PortSwigger/BChecks#83]
I mean there is no way for a console logging somewhere ?

**Comment by A-J-C** [comment]
Hi, we currently don't support console logging, but we will be releasing a more advanced BCheck test editor very soon which should improve how easy it is to develop BChecks.

**Comment by Hannah-PortSwigger** [comment]
Just to let you know, the BChecks testing tool is currently available in Early Adopter (2023.10.2), and will be coming to the Stable channel soon.
