### ISSUE TITLE
Issue with Variable Inclusion in [run for each]

### ISSUE THREAD

**Issue by ayadim** [PortSwigger/BChecks#91]
Hi,
Am trying to define a value then include it in "run for each" the code is validated.I've encountered an issue related to variable inclusion in the loop, it does not send any request at all.
here is me code example:

```
define:
		custom_collaborator = "XXXXX.oast.live"

run for each:
		payload = "shell_exec('ping -c 1 {custom_collaborator}')",`system('ping -c 1 {custom_collaborator}')`
```
i know i can change the collaborator setting but i try to create the same scenario scripts where i add defined variables to "run for each" loop.

regards

_Originally posted by @ayadim in https://github.com/PortSwigger/BChecks/discussions/90_

**Comment by JaveleyQAQ** [comment]
https://github.com/PortSwigger/BChecks/issues/55
