### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 0xspade** [PortSwigger/BChecks#94]
Is it possible to detect a HTTP response with a regex?

**Comment by JaveleyQAQ** [comment]
https://portswigger.net/burp/documentation/scanner/bchecks/bcheck-definition-reference

**Comment by Michelle-PortSwigger** [comment]
The worked examples also include different ways of matching responses that you might find helpful to get you started:
https://portswigger.net/burp/documentation/scanner/bchecks/worked-examples

**Comment by 0xspade** [comment]
Oh I see, what kind of regex does bcheck supports? Java, Python, PHP?

**Comment by JaveleyQAQ** [comment]
> Oh I see, what kind of regex does bcheck supports? Java, Python, PHP?

java

**Comment by 0xspade** [comment]
@Michelle-PortSwigger and team,

I have another question, How to make this bchecks script as a passive scan?

**Comment by JaveleyQAQ** [comment]
> @Michelle-PortSwigger and team,
> 
> I have another question, How to make this bchecks script as a passive scan?

![image](https://github.com/PortSwigger/BChecks/assets/132129852/23dc5e3a-550b-467e-a629-6bd6d2a8cdb1)

**Comment by 0xspade** [comment]
I thought just placing `tags: "passive"` will make it "passive". lol.

**Comment by Michelle-PortSwigger** [comment]
It's about the steps you take within the BCheck, Passive checks are ones that inspect traffic passing through Burp without sending any additional requests. You can find an example one here:
https://portswigger.net/burp/documentation/scanner/bchecks/worked-examples/passive

I hope this helps :)

**Comment by 0xspade** [comment]
@JaveleyQAQ @Michelle-PortSwigger 

Does `appending queries` applies to `GET`, `POST` and other HTTP methods?

If `POST` method, does `appending queries` will append a `POST` data parameter and value?

How about handling JSON?

**Comment by Michelle-PortSwigger** [comment]
Hi

`appending queries` will simply add the query to any URL. If you're looking to make changes to JSON queries that are contained in the body, you'll need to use different techniques. Is there something specific you're working on? If so, feel free to send us an example if you need any help.

**Comment by 0xspade** [comment]
I like to append a parameter if the request method is POST and GET, as well as if the POST data is json or the traditional url encoded.

**Comment by Michelle-PortSwigger** [comment]
`appending queries` will add the query to the URL of GET and POST. If you're wanting to change the parameters contained  as JSON in the body of the request, then you'll probably need to look at using regex to make changes to the body. Please let me know if you have any questions on that side of things.

**Comment by 0xspade** [comment]
Hi Guys,

@JaveleyQAQ @Hannah-PortSwigger @Michelle-PortSwigger 

I have another question, is it possible to put a multiple variable in `run for each`?

**Comment by JaveleyQAQ** [comment]
> Hi Guys,
> 
> @JaveleyQAQ @Hannah-PortSwigger @Michelle-PortSwigger
> 
> I have another question, is it possible to put a multiple variable in `run for each`?

I suggest you observe more scripts in the repository and search for the desired functions. This will deepen your understanding

**Comment by Michelle-PortSwigger** [comment]
@0xspade You can’t do this currently. Run for each is simply running through a list of strings. 

A future feature enhancement may include support for tuples which would make the run for each construct more powerful and hopefully fit your use case.
